; [env:uno]
; platform = atmelavr
; board = uno
; framework = arduino
; ;upload_port = /dev/ttyUSB0
; monitor_speed = 9600
; src_filter = +<resistor.cpp>     
; lib_deps =
;   miguelbalboa/MFRC522@^1.4.0
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

src_filter = +<motor_pwm.cpp>   
upload_speed = 921600
monitor_speed = 115200

lib_deps =
    arduino-libraries/Servo